### ISSUE TITLE
Context in remote resolution

### ISSUE THREAD

**Issue by britram** [mami-project/draft-trammell-post-sockets#25]
Discussing Post Sockets with Benno Overeinder, we realized that since all context in the DNS is implicit, the interface on which a remote resolution occurs via DNS might influence the results of that resolution. Is there anything that the remote needs to do to compensate for this fact?

**Comment by tfpauly** [comment]
It's absolutely true that DNS results can only be cached/compared/etc when looking at one interface (or one DNS server access over that interface). That should be handled by the connection establishment process, which will do the resolution and set up the transients per-path, etc.

I'm going to be updating my 'guidelines' draft this week to make it just about racing during connection establishment, and it addresses isolation of resolution results per-interface. Perhaps once that's ready, we can reference or iterate from there.

**Comment by csperkins** [comment]
Resolve should take a Local?

**Comment by tfpauly** [comment]
The step of resolution must take Remote + Path, where Path includes DNS configuration (servers, search domains, etc, etc)

**Comment by csperkins** [comment]
See #19 for Remote interface
