### ISSUE TITLE
Write down implicit assumptions made about default configurations and compatibility

### ISSUE THREAD

**Issue by chris-wood** [mami-project/draft-trammell-post-sockets#26]
1) Must be possible to use Post Sockets on one side and BSD on the other side                                                                                                                        
2) Carriers must use sane defaults and work without configurations or custom PSCs
3) ...?

**Comment by britram** [comment]
3. must not require signaling beyond that provided by the PSI.
4. "must be implementable" but I don't really think we need to write that down.

**Comment by csperkins** [comment]
5. transport selection magic must give a predictable outcome

**Comment by britram** [comment]
4a. we might want to write down that "must be efficiently implementable in POSIX C without any additional library/kernel support" is a non-goal -- ready() requires asynchronicity, which you can fake without something like libevent, but not in a way that is at all nice.
