### ISSUE TITLE
How to change/set system default (if you don't have an association)?

### ISSUE THREAD

**Issue by mirjak** [mami-project/draft-trammell-post-sockets#27]

**Comment by britram** [comment]
I think the configuration cascade has a system-level root object, followed on multiuser/multicontext systems with a user-level object, followed by application and association defaults.

**Comment by tfpauly** [comment]
This can be the global/application "Context" object, which you may have one or more of, but probably one. #30

**Comment by tfpauly** [comment]
For truly system level, I think it's like sysctls. You probably need to be root, and you probably aren't doing it through Post.
