### ISSUE TITLE
Explain policy

### ISSUE THREAD

**Issue by tfpauly** [mami-project/draft-trammell-post-sockets#6]
Explain usage of policy for post sockets establishment, potentially via referencing a TAPS policy document that is external.

**Comment by britram** [comment]
In this draft, basically we need a block box with an interface.

**Comment by britram** [comment]
I've thought about this a bit more, and I think we should probably point out that policies should have different scopes -- more or less my framing slide from Prague -- but we'll still eventually need an external reference for details.

**Comment by britram** [comment]
this has been folded into #15
