### ISSUE TITLE
Explain/reference transient establishment behavior

### ISSUE THREAD

**Issue by tfpauly** [mami-project/draft-trammell-post-sockets#7]
The transient establishment behavior will likely be an extension of the the TAPS Happy Eyeballs document. Post sockets needs to reference that.

**Comment by csperkins** [comment]
There's also text in the paper that's related (§III.C), that I'll incorporate into the draft.

**Comment by britram** [comment]
This is equivalent to the API dynamics stuff, but pointed downward.
